//----------------------------------------------------------------------
// WARNING: This file was generated by config2cpp. Do not edit.
//----------------------------------------------------------------------

#include "FallbackConfiguration.h"





//--------
// Define the singleton object
//--------
FallbackConfiguration FallbackConfiguration::s_singleton;


FallbackConfiguration::FallbackConfiguration()
{
	m_schema[0] = "connection_timeout = durationSeconds";
	m_schema[1] = "host = string";
	m_schema[2] = "idle_timeout = durationSeconds";
	m_schema[3] = "log = scope";
	m_schema[4] = "log.file = string";
	m_schema[5] = "log.level = int";
	m_schema[6] = "port = int";
	m_schema[7] = "rpc_timeout = durationMilliseconds";
	m_schema[8] = 0;

	m_str << "#-------------------------------------------------";
	m_str << "----------------------\n";
	m_str << "# File:        DefaultFooConfigString.cfg\n";
	m_str << "#\n";
	m_str << "# Description: Default configuration values for Fo";
	m_str << "o.\n";
	m_str << "#-------------------------------------------------";
	m_str << "----------------------\n";
	m_str << "\n";
	m_str << "connection_timeout = \"10 seconds\";\n";
	m_str << "rpc_timeout = \"200 milliseconds\";\n";
	m_str << "idle_timeout = \"10 minutes\";\n";
	m_str << "host = exec(\"hostname\", \"localhost\");\n";
	m_str << "port = \"12345\";\n";
	m_str << "log {\n";
	m_str << "\tlevel = \"1\";\n";
	m_str << "\t@if (getenv(\"FOO_HOME\", \"\") == \"\") {\n";
	m_str << "\t\tfile = \"foo.log\";\n";
	m_str << "\t} @else {\n";
	m_str << "\t\tfile = getenv(\"FOO_HOME\") + \"/logs/foo.log\";\n";
	m_str << "\t}\n";
	m_str << "}\n";
	m_str << "";
}





FallbackConfiguration::~FallbackConfiguration()
{
	// Nothing to do
}


